name: tests

on: [push, pull_request]

jobs:
  test-image-builds:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker image build -t lex:build-test ./lex
